pl1_linux_hosts:
  hosts:
    pl1-1:
      ansible_host: sirpl1-01-linux.local
    pl1-2:
      ansible_host: sirpl1-02-linux.local
    pl1-3:
      ansible_host: sirpl1-03-linux.local
    pl1-4:
      ansible_host: sirpl1-04-linux.local
    pl1-5:
      ansible_host: sirpl1-05-linux.local
    pl1-6:
      ansible_host: sirpl1-06-linux.local
    pl1-7:
      ansible_host: sirpl1-07-linux.local
    pl1-8:
      ansible_host: sirpl1-08-linux.local
    pl1-9:
      ansible_host: sirpl1-09-linux.local
    pl1-10:
      ansible_host: sirpl1-10-linux.local
    pl1-11:
      ansible_host: sirpl1-11-linux.local
    pl1-12:
      ansible_host: sirpl1-12-linux.local
    pl1-13:
      ansible_host: sirpl1-13-linux.local
    pl1-14:
      ansible_host: sirpl1-14-linux.local
    pl1-15:
      ansible_host: sirpl1-15-linux.local  
    pl1-16:
      ansible_host: sirpl1-16-linux.local
    pl1-17:
      ansible_host: sirpl1-17-linux.local
    pl1-18:
      ansible_host: sirpl1-18-linux.local
    pl1-19:
      ansible_host: sirpl1-19-linux.local
    pl1-20:
      ansible_host: sirpl1-20-linux.local
    pl1-21:
      ansible_host: sirpl1-21-linux.local
    pl1-22:
      ansible_host: sirpl1-22-linux.local
    pl1-23:
      ansible_host: sirpl1-23-linux.local
    pl1-24:
      ansible_host: sirpl1-24-linux.local
    pl1-25:
      ansible_host: sirpl1-25-linux.local
    pl1-26:
      ansible_host: sirpl1-26-linux.local
    pl1-27:
      ansible_host: sirpl1-27-linux.local
    pl1-28:
      ansible_host: sirpl1-28-linux.local
    pl1-29:
      ansible_host: sirpl1-29-linux.local
    pl1-30:
      ansible_host: sirpl1-30-linux.local
    pl1-31:
      ansible_host: sirpl1-31-linux.local
    pl1-32:
      ansible_host: sirpl1-32-linux.local
    pl1-33:
      ansible_host: sirpl1-33-linux.local
    pl1-34:
      ansible_host: sirpl1-34-linux.local
    pl1-35:
      ansible_host: sirpl1-35-linux.local
    pl1-36:
      ansible_host: sirpl1-36-linux.local
    pl1-37:
      ansible_host: sirpl1-37-linux.local
    pl1-38:
      ansible_host: sirpl1-38-linux.local
    pl1-39:
      ansible_host: sirpl1-39-linux.local
    pl1-40:
      ansible_host: sirpl1-40-linux.local
    pl1-41:
      ansible_host: sirpl1-41-linux.local
    pl1-42:
      ansible_host: sirpl1-42-linux.local
    pl1-43:
      ansible_host: sirpl1-43-linux.local
    pl1-44:
      ansible_host: sirpl1-44-linux.local
    pl1-45:
      ansible_host: sirpl1-45-linux.local  
    pl1-46:
      ansible_host: sirpl1-46-linux.local
    pl1-47:
      ansible_host: sirpl1-47-linux.local
    pl1-48:
      ansible_host: sirpl1-48-linux.local
    pl1-49:
      ansible_host: sirpl1-49-linux.local
    pl1-50:
      ansible_host: sirpl1-50-linux.local
    pl1-51:
      ansible_host: sirpl1-51-linux.local
    pl1-52:
      ansible_host: sirpl1-52-linux.local
    pl1-53:
      ansible_host: sirpl1-53-linux.local
    pl1-54:
      ansible_host: sirpl1-54-linux.local
    pl1-55:
      ansible_host: sirpl1-55-linux.local
    pl1-56:
      ansible_host: sirpl1-56-linux.local
    pl1-57:
      ansible_host: sirpl1-57-linux.local
    pl1-58:
      ansible_host: sirpl1-58-linux.local
    pl1-59:
      ansible_host: sirpl1-59-linux.local
    pl1-60:
      ansible_host: sirpl1-60-linux.local  

  vars:
    ansible_user: ladmin
